"""Add Data and DateTime to OctCSV Table

Revision ID: 0411ced1ec8c
Revises: c78d07dcd03f
Create Date: 2021-08-19 17:35:25.282509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0411ced1ec8c'
down_revision = 'c78d07dcd03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
