"""Added material to settings

Revision ID: 0546d65ba79e
Revises: 44f316a89c63
Create Date: 2021-10-04 10:06:47.255012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0546d65ba79e'
down_revision = '44f316a89c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('material', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'material')
    # ### end Alembic commands ###
