"""User Migration

Revision ID: 1a14632ff1e2
Revises: 934a88f2be95
Create Date: 2021-08-12 12:49:28.310902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a14632ff1e2'
down_revision = '934a88f2be95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
