"""Add Data to OctCSV Table

Revision ID: 2169eb4f6609
Revises: 70cd017ecec2
Create Date: 2021-08-20 13:00:55.433593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2169eb4f6609'
down_revision = '70cd017ecec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('octcsv', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('octcsv', 'data')
    # ### end Alembic commands ###
