"""OCTCSV remove seamid foreignkey

Revision ID: 3a19867de601
Revises: 79892bbcccfe
Create Date: 2021-08-24 19:35:55.735957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a19867de601'
down_revision = '79892bbcccfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('octcsv_seamid_fkey', 'octcsv', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('octcsv_seamid_fkey', 'octcsv', 'laserpar', ['seamid'], ['seamid'])
    # ### end Alembic commands ###
