"""Reset Tables

Revision ID: 3fb2a6f6ab10
Revises: 3a19867de601
Create Date: 2021-08-24 21:25:04.190150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb2a6f6ab10'
down_revision = '3a19867de601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laserpar', sa.Column('octcsv_id', sa.Integer(), nullable=True))
    op.drop_constraint('laserpar_seamid_key', 'laserpar', type_='unique')
    op.create_foreign_key(None, 'laserpar', 'octcsv', ['octcsv_id'], ['id'])
    op.drop_column('laserpar', 'seamid')
    op.alter_column('octcsv', 'seamid',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('octcsv', 'seamid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('laserpar', sa.Column('seamid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'laserpar', type_='foreignkey')
    op.create_unique_constraint('laserpar_seamid_key', 'laserpar', ['seamid'])
    op.drop_column('laserpar', 'octcsv_id')
    # ### end Alembic commands ###
