"""Added laser fields

Revision ID: 44f316a89c63
Revises: 1bdb59bf18f7
Create Date: 2021-10-04 09:41:14.424302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f316a89c63'
down_revision = '1bdb59bf18f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('part_number', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('laser_programm', sa.Integer(), nullable=True))
    op.add_column('settings', sa.Column('ramp_length', sa.Float(), nullable=True))
    op.add_column('settings', sa.Column('ramp_type', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('laser_power', sa.Float(), nullable=True))
    op.add_column('settings', sa.Column('puls_duration', sa.Float(), nullable=True))
    op.add_column('settings', sa.Column('fiber_diameter', sa.Float(), nullable=True))
    op.add_column('settings', sa.Column('sheet_1_height', sa.Float(), nullable=True))
    op.add_column('settings', sa.Column('sheet_2_height', sa.Float(), nullable=True))
    op.add_column('settings', sa.Column('sheet_3_height', sa.Float(), nullable=True))
    op.add_column('settings', sa.Column('gap_1', sa.Float(), nullable=True))
    op.add_column('settings', sa.Column('gap_2', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'gap_2')
    op.drop_column('settings', 'gap_1')
    op.drop_column('settings', 'sheet_3_height')
    op.drop_column('settings', 'sheet_2_height')
    op.drop_column('settings', 'sheet_1_height')
    op.drop_column('settings', 'fiber_diameter')
    op.drop_column('settings', 'puls_duration')
    op.drop_column('settings', 'laser_power')
    op.drop_column('settings', 'ramp_type')
    op.drop_column('settings', 'ramp_length')
    op.drop_column('settings', 'laser_programm')
    op.drop_column('settings', 'part_number')
    # ### end Alembic commands ###
