"""CsvData delete cascade v4 Table

Revision ID: 5dec1c516008
Revises: ba7dbffc9d1c
Create Date: 2021-08-20 16:19:38.797046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dec1c516008'
down_revision = 'ba7dbffc9d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('octcsv_userid_fkey', 'octcsv', type_='foreignkey')
    op.create_foreign_key(None, 'octcsv', 'user', ['userid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'octcsv', type_='foreignkey')
    op.create_foreign_key('octcsv_userid_fkey', 'octcsv', 'user', ['userid'], ['id'])
    # ### end Alembic commands ###
