"""Add CsvData v2 Table

Revision ID: 658a954d6896
Revises: 4c8f3c3a9b43
Create Date: 2021-08-20 15:43:40.642574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658a954d6896'
down_revision = '4c8f3c3a9b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
