"""Adding OCTPar Table

Revision ID: 69727dcb6352
Revises: 24676f0b38bb
Create Date: 2021-08-21 13:11:47.567088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69727dcb6352'
down_revision = '24676f0b38bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laserpar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('octcsv_id', sa.Integer(), nullable=True),
    sa.Column('seam_length', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('step_size_oct_tester', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['octcsv_id'], ['octcsv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('octparparallel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('octcsv_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('points_per_line', sa.Integer(), nullable=True),
    sa.Column('points_per_interval', sa.Integer(), nullable=True),
    sa.Column('line_length', sa.Float(), nullable=True),
    sa.Column('extend_points', sa.Integer(), nullable=True),
    sa.Column('reference_points', sa.Integer(), nullable=True),
    sa.Column('extend_reference_points', sa.Integer(), nullable=True),
    sa.Column('lag_xy', sa.Float(), nullable=True),
    sa.Column('x_start', sa.Float(), nullable=True),
    sa.Column('x_end', sa.Float(), nullable=True),
    sa.Column('y_start', sa.Float(), nullable=True),
    sa.Column('y_end', sa.Float(), nullable=True),
    sa.Column('x_ref_coordinate', sa.Float(), nullable=True),
    sa.Column('y_ref_coordinate', sa.Float(), nullable=True),
    sa.Column('jump_speed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['octcsv_id'], ['octcsv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('octparparallel')
    op.drop_table('laserpar')
    # ### end Alembic commands ###
