"""Add Data and DateTime to OctCSV Table

Revision ID: 7388d7dc0996
Revises: d21e935b9bb5
Create Date: 2021-08-19 12:31:21.449403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7388d7dc0996'
down_revision = 'd21e935b9bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('octcsv', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.add_column('octcsv', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('octcsv', 'seamid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'octcsv', ['seamid'])
    op.drop_column('octcsv', 'time')
    op.drop_column('octcsv', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('octcsv', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('octcsv', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'octcsv', type_='unique')
    op.alter_column('octcsv', 'seamid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('octcsv', 'data')
    op.drop_column('octcsv', 'datetime')
    # ### end Alembic commands ###
