"""Filename added to octcsv Table

Revision ID: 7866629b41ea
Revises: 118ed4ccbf4d
Create Date: 2021-08-21 11:37:43.274766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7866629b41ea'
down_revision = '118ed4ccbf4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('octcsv', sa.Column('filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('octcsv', 'filename')
    # ### end Alembic commands ###
