"""LaserPar ForeignKey seamid

Revision ID: 79892bbcccfe
Revises: f06c66def447
Create Date: 2021-08-24 19:26:19.170563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79892bbcccfe'
down_revision = 'f06c66def447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laserpar', sa.Column('seamid', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'laserpar', ['seamid'])
    op.drop_constraint('laserpar_octcsv_id_fkey', 'laserpar', type_='foreignkey')
    op.drop_column('laserpar', 'octcsv_id')
    op.alter_column('octcsv', 'seamid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'octcsv', 'laserpar', ['seamid'], ['seamid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'octcsv', type_='foreignkey')
    op.alter_column('octcsv', 'seamid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('laserpar', sa.Column('octcsv_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('laserpar_octcsv_id_fkey', 'laserpar', 'octcsv', ['octcsv_id'], ['id'])
    op.drop_constraint(None, 'laserpar', type_='unique')
    op.drop_column('laserpar', 'seamid')
    # ### end Alembic commands ###
