"""add scope to users table

Revision ID: 7d8d481e5f9e
Revises: 4cd51d3f2899
Create Date: 2021-08-09 13:46:25.479721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d8d481e5f9e'
down_revision = '4cd51d3f2899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('scope', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'scope')
    # ### end Alembic commands ###
