"""Scoper as String

Revision ID: 8af3ac76ddd5
Revises: 1a14632ff1e2
Create Date: 2021-08-12 12:51:27.390017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af3ac76ddd5'
down_revision = '1a14632ff1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
