"""User Migration

Revision ID: 934a88f2be95
Revises: 7d8d481e5f9e
Create Date: 2021-08-10 08:38:56.656674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934a88f2be95'
down_revision = '7d8d481e5f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
