"""Add Type to OctCSV Table

Revision ID: 93c3526b1071
Revises: 0411ced1ec8c
Create Date: 2021-08-19 20:54:18.414398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c3526b1071'
down_revision = '0411ced1ec8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('octcsv', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('octcsv', 'type')
    # ### end Alembic commands ###
