"""added sheet material

Revision ID: 93c4d3481dc6
Revises: a2fa51ab9ba0
Create Date: 2021-10-04 10:32:20.120949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c4d3481dc6'
down_revision = 'a2fa51ab9ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laserpar', sa.Column('sheet_1_material', sa.String(), nullable=True))
    op.add_column('laserpar', sa.Column('sheet_2_material', sa.String(), nullable=True))
    op.add_column('laserpar', sa.Column('sheet_3_material', sa.String(), nullable=True))
    op.drop_column('laserpar', 'material')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laserpar', sa.Column('material', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('laserpar', 'sheet_3_material')
    op.drop_column('laserpar', 'sheet_2_material')
    op.drop_column('laserpar', 'sheet_1_material')
    # ### end Alembic commands ###
