"""Add laser_id to OCTPar

Revision ID: 9f4028691f76
Revises: baa1f961d512
Create Date: 2021-09-01 17:09:01.637717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4028691f76'
down_revision = 'baa1f961d512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('octpar', sa.Column('laser_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'octpar', 'laserpar', ['laser_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'octpar', type_='foreignkey')
    op.drop_column('octpar', 'laser_id')
    # ### end Alembic commands ###
