"""laser_programm to laser_program

Revision ID: a2fa51ab9ba0
Revises: 9b7fa51c609d
Create Date: 2021-10-04 10:31:04.632508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2fa51ab9ba0'
down_revision = '9b7fa51c609d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laserpar', sa.Column('laser_program', sa.Integer(), nullable=True))
    op.drop_column('laserpar', 'laser_programm')
    op.add_column('settings', sa.Column('laser_program', sa.Integer(), nullable=True))
    op.drop_column('settings', 'laser_programm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('laser_programm', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('settings', 'laser_program')
    op.add_column('laserpar', sa.Column('laser_programm', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('laserpar', 'laser_program')
    # ### end Alembic commands ###
