"""Create Settings Table

Revision ID: a5face616faa
Revises: 9f4028691f76
Create Date: 2021-09-01 18:03:53.571890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5face616faa'
down_revision = '9f4028691f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('points_per_line', sa.Integer(), nullable=True),
    sa.Column('points_per_interval', sa.Integer(), nullable=True),
    sa.Column('line_length', sa.Float(), nullable=True),
    sa.Column('extend_points', sa.Integer(), nullable=True),
    sa.Column('reference_points', sa.Integer(), nullable=True),
    sa.Column('extend_reference_points', sa.Integer(), nullable=True),
    sa.Column('lag_xy', sa.Float(), nullable=True),
    sa.Column('x_start', sa.Float(), nullable=True),
    sa.Column('x_end', sa.Float(), nullable=True),
    sa.Column('y_start', sa.Float(), nullable=True),
    sa.Column('y_end', sa.Float(), nullable=True),
    sa.Column('x_ref_coordinate', sa.Float(), nullable=True),
    sa.Column('y_ref_coordinate', sa.Float(), nullable=True),
    sa.Column('jump_speed', sa.Float(), nullable=True),
    sa.Column('seam_length', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('step_size_oct_tester', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
