"""Not unique Seam ID in OctCSV Table

Revision ID: b038327b6b48
Revises: 2169eb4f6609
Create Date: 2021-08-20 13:04:29.874860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b038327b6b48'
down_revision = '2169eb4f6609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('octcsv_seamid_key', 'octcsv', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('octcsv_seamid_key', 'octcsv', ['seamid'])
    # ### end Alembic commands ###
