"""CsvData delete cascade v2 Table

Revision ID: b6de254409cf
Revises: f1cd16319225
Create Date: 2021-08-20 16:11:07.078775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6de254409cf'
down_revision = 'f1cd16319225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
