"""Adding seamid to LaserPar Table

Revision ID: b91af79961f4
Revises: d089035cbbb1
Create Date: 2021-08-23 11:40:12.434676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91af79961f4'
down_revision = 'd089035cbbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laserpar', sa.Column('seam_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laserpar', 'seam_id')
    # ### end Alembic commands ###
