"""CsvData delete cascade v3 Table

Revision ID: ba7dbffc9d1c
Revises: b6de254409cf
Create Date: 2021-08-20 16:15:19.301090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7dbffc9d1c'
down_revision = 'b6de254409cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
