"""Reset Tables

Revision ID: baa1f961d512
Revises: 3fb2a6f6ab10
Create Date: 2021-08-24 21:27:21.741537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'baa1f961d512'
down_revision = '3fb2a6f6ab10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('octcsv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('seamid', sa.Integer(), nullable=False),
    sa.Column('linenumber', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('grouporder', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csvdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('octcsv_id', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['octcsv_id'], ['octcsv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laserpar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('octcsv_id', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('seam_id', sa.Integer(), nullable=True),
    sa.Column('seam_length', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('step_size_oct_tester', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['octcsv_id'], ['octcsv.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('octpar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('octcsv_id', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('points_per_line', sa.Integer(), nullable=True),
    sa.Column('points_per_interval', sa.Integer(), nullable=True),
    sa.Column('line_length', sa.Float(), nullable=True),
    sa.Column('extend_points', sa.Integer(), nullable=True),
    sa.Column('reference_points', sa.Integer(), nullable=True),
    sa.Column('extend_reference_points', sa.Integer(), nullable=True),
    sa.Column('lag_xy', sa.Float(), nullable=True),
    sa.Column('x_start', sa.Float(), nullable=True),
    sa.Column('x_end', sa.Float(), nullable=True),
    sa.Column('y_start', sa.Float(), nullable=True),
    sa.Column('y_end', sa.Float(), nullable=True),
    sa.Column('x_ref_coordinate', sa.Float(), nullable=True),
    sa.Column('y_ref_coordinate', sa.Float(), nullable=True),
    sa.Column('jump_speed', sa.Float(), nullable=True),
    sa.Column('scantype', sa.String(), nullable=True),
    sa.Column('grouporder', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['octcsv_id'], ['octcsv.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('octpar')
    op.drop_table('laserpar')
    op.drop_table('csvdata')
    op.drop_table('octcsv')
    # ### end Alembic commands ###
