"""Add Data and DateTime to OctCSV Table

Revision ID: c78d07dcd03f
Revises: 7388d7dc0996
Create Date: 2021-08-19 17:08:21.330909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78d07dcd03f'
down_revision = '7388d7dc0996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
