"""CsvData delete cascade v5 Table

Revision ID: ca80a7686df8
Revises: 5dec1c516008
Create Date: 2021-08-20 16:25:45.665311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca80a7686df8'
down_revision = '5dec1c516008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
