"""Adding userid relationship to all Tables

Revision ID: d089035cbbb1
Revises: e687aceec731
Create Date: 2021-08-23 11:09:44.428832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd089035cbbb1'
down_revision = 'e687aceec731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laserpar', sa.Column('userid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'laserpar', 'user', ['userid'], ['id'], ondelete='CASCADE')
    op.add_column('octpar', sa.Column('userid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'octpar', 'user', ['userid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'octpar', type_='foreignkey')
    op.drop_column('octpar', 'userid')
    op.drop_constraint(None, 'laserpar', type_='foreignkey')
    op.drop_column('laserpar', 'userid')
    # ### end Alembic commands ###
