"""Adding grouporder to OCTPar Table

Revision ID: e687aceec731
Revises: e6b057208956
Create Date: 2021-08-23 10:48:04.851175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e687aceec731'
down_revision = 'e6b057208956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('octpar', sa.Column('grouporder', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('octpar', 'grouporder')
    # ### end Alembic commands ###
