"""Adding scantype to OCTPar Table

Revision ID: e6b057208956
Revises: f4058b4b20e6
Create Date: 2021-08-21 17:31:36.508518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b057208956'
down_revision = 'f4058b4b20e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('octpar', sa.Column('scantype', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('octpar', 'scantype')
    # ### end Alembic commands ###
