"""CsvData delete cascade Table

Revision ID: f1cd16319225
Revises: 658a954d6896
Create Date: 2021-08-20 16:06:32.385490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1cd16319225'
down_revision = '658a954d6896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
