"""Adding OCTPar v2 Table

Revision ID: f4058b4b20e6
Revises: 69727dcb6352
Create Date: 2021-08-21 13:13:23.179104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4058b4b20e6'
down_revision = '69727dcb6352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('octpar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('octcsv_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('points_per_line', sa.Integer(), nullable=True),
    sa.Column('points_per_interval', sa.Integer(), nullable=True),
    sa.Column('line_length', sa.Float(), nullable=True),
    sa.Column('extend_points', sa.Integer(), nullable=True),
    sa.Column('reference_points', sa.Integer(), nullable=True),
    sa.Column('extend_reference_points', sa.Integer(), nullable=True),
    sa.Column('lag_xy', sa.Float(), nullable=True),
    sa.Column('x_start', sa.Float(), nullable=True),
    sa.Column('x_end', sa.Float(), nullable=True),
    sa.Column('y_start', sa.Float(), nullable=True),
    sa.Column('y_end', sa.Float(), nullable=True),
    sa.Column('x_ref_coordinate', sa.Float(), nullable=True),
    sa.Column('y_ref_coordinate', sa.Float(), nullable=True),
    sa.Column('jump_speed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['octcsv_id'], ['octcsv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('octparparallel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('octparparallel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('octcsv_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('frequency', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('points_per_line', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('points_per_interval', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('line_length', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extend_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extend_reference_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lag_xy', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('x_start', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('x_end', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('y_start', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('y_end', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('x_ref_coordinate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('y_ref_coordinate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('jump_speed', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['octcsv_id'], ['octcsv.id'], name='octparparallel_octcsv_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='octparparallel_pkey')
    )
    op.drop_table('octpar')
    # ### end Alembic commands ###
